version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: "postgresql://postgres:P@ssw0rd@db:5432/mydatabase"
      JWT_SECRET: "seuSegredoJWTsuperseguro"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn tsnd --respawn --transpile-only src/server.ts
    deploy:
      resources:
        limits:
          memory: 512M # Ajuste conforme necessário

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
